<?php
declare(strict_types=1);

namespace CannonMiner;

use DateTimeImmutable;
use PDO;
use RuntimeException;

final class Simulator
{
    public const DEFAULT_DRIVER_NAMES=['Doug Tabbut','Dunadel Daryoush','Arne Toman','Chris Duerden','Safi Barqawi','Chris Benvie','James Allen','Kale Odhner','Samuel Lurie','Chris Allen','Matt Fried','Christopher Stowell','Berkeley Chadwick','Carl Dietz','Jason Adkins','Mark Spence','Sean Petr','Dave Black','Dan Huang','Ed Bolian','Stephen Thomas','Tommy Thomas','Steven Groh','Troy Schneider','Andrew Calore','Ryan Stark','David Risch','Nik Krueger','Wesley Vigh','Christopher Michael','Tommy Davies','Rob Pickup','Robert Pryer','Romuald Clariond','Seth Rose','Cameron Davis','Aaron Tulin','Alex Roy','Dave Maher','Cory Welles','John Levie','Joe Petralia','Yumi Dietz','Ben Preston','Elijah Dietz','Taylor Hull','Hunter Robinson','Andrew Rodgers','Scott Saier','Tim Daley','William Shafer','Miles Compton','Syed Ahmed','Travis Hilton','Art Ashmore','Fred Ashmore','Chris Taylor','Adam Swetlik','Richard Rawlings','Dennis Collins'];
    public const LOCATIONS=['redball'=>'Redball Garage, NY','portofino'=>'Portofino Marina, CA','bar'=>'Barstow, CA','big'=>'Big Springs, NE','cole'=>'Columbus East, OH','coln'=>'Columbus North, OH','cov'=>'Cove Fort, UT','den'=>'Denver, CO','elr'=>'El Reno, OK','har'=>'Harrisburg, PA','nash'=>'Nashville, TN','stl'=>'St. Louis, IL','you'=>'Youngstown, OH'];

    public function __construct(private PDO $pdo,private RouteGraph $graph,private SimulationTrafficProvider $traffic,private Settings $settings){}

    public function roster(string $username):array
    {
        $configured=(string)$this->settings->get('simulator_driver_names',implode("\n",self::DEFAULT_DRIVER_NAMES));$names=[];
        foreach(preg_split('/\R/u',$configured)?:[] as $name){$name=trim($name);if($name!==''&&strcasecmp($name,$username)!==0&&!in_array(strtolower($name),array_map('strtolower',$names),true))$names[]=$name;}
        if(count($names)<6)$names=self::DEFAULT_DRIVER_NAMES;
        shuffle($names);$drivers=[self::driver('self',$username,true)];
        for($i=0;$i<6;$i++)$drivers[]=self::driver('candidate-'.$i,$names[$i],false);
        return$drivers;
    }

    private static function driver(string $id,string $name,bool $required):array
    {
        return['id'=>$id,'name'=>$name,'required'=>$required,'endurance'=>random_int(45,95),'driving'=>random_int(45,95),'copilot'=>random_int(45,95)];
    }

    public static function locationName(string $node):string{return self::LOCATIONS[$node]??ucwords(str_replace('_',' ',$node));}
    public static function routeName(string $segment):string{$parts=explode('_to_',$segment,2);return count($parts)===2?self::locationName($parts[0]).' to '.self::locationName($parts[1]):$segment;}
    public static function routeLabel(array $segments):string
    {
        $nodes=[];
        foreach($segments as $segment){$parts=explode('_to_',(string)$segment,2);if(count($parts)!==2)continue;if(!$nodes)$nodes[]=$parts[0];$nodes[]=$parts[1];}
        return implode(' → ',array_map([self::class,'locationName'],$nodes));
    }

    public function cars():array{$rows=$this->pdo->query('SELECT id,name,mpg_below_35,mpg_35_70,mpg_above_70,capacity,top_speed,tuned_top_speed,max_fuel_cells,max_load,lemon,image_path FROM simulator_vehicles ORDER BY name')->fetchAll();foreach($rows as &$row){foreach(['mpg_below_35','mpg_35_70','mpg_above_70','capacity','top_speed','tuned_top_speed','lemon'] as $key)$row[$key]=(float)$row[$key];foreach(['max_fuel_cells','max_load'] as $key)$row[$key]=(int)$row[$key];}unset($row);return$rows;}
    public function loadCosts():array{$values=$this->settings->all();$defaults=['driver'=>200,'fuel_cell'=>200,'additional_spare'=>200,'cruising_tires'=>0,'cruising_tune'=>50,'tuned_up'=>0,'radio_scanner'=>1,'radar_scanner'=>5,'radar_jammer'=>25,'police_camo'=>50,'thermal_camera'=>25,'redbull_cooler'=>25,'snack'=>20];foreach($defaults as $key=>$default)$defaults[$key]=max(0,(int)($values['simulator_load_'.$key]??$default));return$defaults;}
    public function supportsDeparture(string $value):bool{$departure=DateTimeImmutable::createFromFormat('!Y-m-d\TH:i',$value,new \DateTimeZone('America/New_York'));return$departure!==false&&$departure->format('Y-m-d\TH:i')===$value&&$this->traffic->hasEvidenceForDate($departure);}

    public function create(int $userId,array $input,array $roster):string
    {
        $mode=in_array($input['mode']??'',['realtime','arcade'],true)?$input['mode']:'arcade';$minigamesEnabled=isset($input['minigames']);
        $departureText=(string)($input['departure']??'');$departure=DateTimeImmutable::createFromFormat('!Y-m-d\TH:i',$departureText,new \DateTimeZone('America/New_York'));
        if(!$departure||$departure->format('Y-m-d\TH:i')!==$departureText)throw new RuntimeException('Choose a valid departure date and time.');
        if(!$this->supportsDeparture($departureText))throw new RuntimeException('No directly supported traffic data is available for the selected departure day. Choose another date.');
        $carId=(string)($input['car']??'');$lookup=$this->pdo->prepare('SELECT name,mpg_below_35,mpg_35_70,mpg_above_70,capacity,top_speed,tuned_top_speed,max_fuel_cells,max_load,lemon,image_path FROM simulator_vehicles WHERE id=?');$lookup->execute([$carId]);$car=$lookup->fetch();if(!$car)throw new RuntimeException('Choose an available car.');foreach(['mpg_below_35','mpg_35_70','mpg_above_70','capacity','top_speed','tuned_top_speed','lemon'] as $key)$car[$key]=(float)$car[$key];foreach(['max_fuel_cells','max_load'] as $key)$car[$key]=(int)$car[$key];$speed=max(20,min(250,(float)($input['speed']??110)));
        $fuelCells=max(0,min((int)$car['max_fuel_cells'],(int)($input['fuel_cells']??0)));$snacks=max(0,min(1000,(int)($input['snacks']??0)));$tuned=isset($input['cruising_tune']);$tunedUp=isset($input['tuned_up']);$cruisingTires=isset($input['cruising_tires']);$additionalSpare=isset($input['additional_spare']);$radioScanner=isset($input['radio_scanner']);$radarScanner=isset($input['radar_scanner']);$radarJammer=isset($input['radar_jammer']);$policeCamo=isset($input['police_camo']);$thermalCamera=isset($input['thermal_camera']);$redbullCooler=isset($input['redbull_cooler']);if($radarJammer&&!$radarScanner)throw new RuntimeException('The Radar Jammer requires a Radar Scanner.');$equipmentCost=$fuelCells*300+$snacks*15+($tuned?1500:0)+($tunedUp?2000:0)+($cruisingTires?1500:0)+($additionalSpare?500:0)+($radioScanner?250:0)+($radarScanner?600:0)+($radarJammer?1000:0)+($policeCamo?1000:0)+($thermalCamera?500:0)+($redbullCooler?35:0);$equipment=['fuel_cells'=>$fuelCells,'snacks'=>$snacks,'cruising_tune'=>$tuned,'tuned_up'=>$tunedUp,'cruising_tires'=>$cruisingTires,'additional_spare'=>$additionalSpare,'additional_spare_consumed'=>false,'radio_scanner'=>$radioScanner,'radar_scanner'=>$radarScanner,'radar_jammer'=>$radarJammer,'police_camo'=>$policeCamo,'thermal_camera'=>$thermalCamera,'redbull_cooler'=>$redbullCooler,'cost'=>$equipmentCost];
        $selected=array_map('strval',(array)($input['drivers']??[]));$initialDriver=(string)($input['initial_driver']??'self');$drivers=[];
        foreach($roster as $candidate)if($candidate['required']||in_array($candidate['id'],$selected,true))$drivers[]=$candidate+['role'=>$candidate['id']===$initialDriver?'driver':'rest','fatigue'=>0.0,'rest_seconds'=>0.0,'role_seconds'=>['driver'=>0.0,'copilot'=>0.0,'rest'=>0.0,'total'=>0.0],'consumable_uses'=>[],'active_effects'=>[],'redbull_penalties'=>[],'locked_rest'=>false];
        if(count($drivers)>3)throw new RuntimeException('Choose no more than two additional drivers.');
        if(!in_array($initialDriver,array_column($drivers,'id'),true))throw new RuntimeException('Choose an initial driver from the selected roster.');
        $loadCosts=$this->loadCosts();$loadUsed=count($drivers)*$loadCosts['driver']+$fuelCells*$loadCosts['fuel_cell']+$snacks*$loadCosts['snack']+($additionalSpare?$loadCosts['additional_spare']:0)+($cruisingTires?$loadCosts['cruising_tires']:0)+($tuned?$loadCosts['cruising_tune']:0)+($tunedUp?$loadCosts['tuned_up']:0)+($radioScanner?$loadCosts['radio_scanner']:0)+($radarScanner?$loadCosts['radar_scanner']:0)+($radarJammer?$loadCosts['radar_jammer']:0)+($policeCamo?$loadCosts['police_camo']:0)+($thermalCamera?$loadCosts['thermal_camera']:0)+($redbullCooler?$loadCosts['redbull_cooler']:0);if($loadUsed>$car['max_load'])throw new RuntimeException(sprintf('The selected crew and equipment exceed this vehicle\'s maximum load by %d.',$loadUsed-$car['max_load']));
        $seed=random_int(1,2147483647);$choices=$this->choicePayload('redball');if(!$choices)throw new RuntimeException('No supported route begins at Red Ball.');
        $state=['node'=>'redball','route'=>[],'traveled_segments'=>[],'choices'=>$choices,'current_segment'=>null,'active_weather'=>null,'active_invented_traffic'=>null,'active_wildlife_slowdown'=>null,'drivers'=>$drivers,'driver_copilot'=>false,'pending_decision'=>['type'=>'route'],'departure_at'=>$departure->format(DATE_ATOM),'minigames_enabled'=>$minigamesEnabled,
            'vehicle'=>['car_id'=>$carId,'name'=>$car['name'],'image_path'=>$car['image_path'],'capacity'=>$car['capacity']+$fuelCells*20,'fuel'=>$car['capacity']+$fuelCells*20,'mpg_below_35'=>$car['mpg_below_35']+($cruisingTires?1:0),'mpg_35_70'=>$car['mpg_35_70']+($cruisingTires?1:0),'mpg_above_70'=>$car['mpg_above_70']+($cruisingTires?1:0)+($tuned?5:0),'top_speed'=>$car['top_speed'],'tuned_top_speed'=>$car['tuned_top_speed'],'tuned'=>$tuned,'lemon'=>$tunedUp?1.0:$car['lemon'],'base_lemon'=>$car['lemon'],'max_fuel_cells'=>$car['max_fuel_cells'],'fuel_cells'=>$fuelCells,'max_load'=>$car['max_load'],'load_used'=>$loadUsed,'load_remaining'=>$car['max_load']-$loadUsed,'target_speed'=>$speed,'current_speed'=>0.0,'distance_miles'=>0.0,'stopped_seconds'=>0.0],
            'equipment'=>$equipment,'consumables'=>array_filter(['redbull'=>$redbullCooler?['name'=>'RedBull','icon'=>'🥤','remaining'=>6,'maximum_per_driver'=>4,'effect_seconds'=>7200]:null,'snack'=>$snacks>0?['name'=>'Snack','icon'=>'🍿','remaining'=>$snacks,'maximum_per_driver'=>5,'fatigue_reduction'=>5]:null]),'notification_queue'=>[],'run_metrics'=>['fuel_stops'=>0,'fuel_consumed'=>0.0,'police_encounters'=>0],'flat_tires_repaired'=>0,'last_speed_for_warning'=>$this->vehicleSpeedLimit(['target_speed'=>$speed,'top_speed'=>$car['top_speed'],'tuned_top_speed'=>$car['tuned_top_speed'],'tuned'=>$tuned]),'started'=>false,'traffic_mode'=>$departure<new DateTimeImmutable('now')?'recorded':'projected','event_chances'=>$this->eventChances()];
        $id=bin2hex(random_bytes(16));$this->pdo->beginTransaction();
        try{$this->pdo->prepare("INSERT INTO simulations(id,user_id,status,mode,departure_at,simulated_at,random_seed,state) VALUES (?,?,'awaiting_route',?,?,?,?,?::jsonb)")
                ->execute([$id,$userId,$mode,$departure->format(DATE_ATOM),$departure->format(DATE_ATOM),$seed,json_encode($state,JSON_THROW_ON_ERROR)]);
            $this->event($id,$departure,'simulation_created',['mode'=>$mode,'traffic_mode'=>$state['traffic_mode']]);$this->pdo->commit();return$id;
        }catch(\Throwable $error){$this->pdo->rollBack();throw$error;}
    }

    public function tick(string $id):void
    {
        $this->pdo->beginTransaction();try{$statement=$this->pdo->prepare("SELECT * FROM simulations WHERE id=? FOR UPDATE");$statement->execute([$id]);$simulation=$statement->fetch();
        if(!$simulation||$simulation['status']!=='running'){$this->pdo->commit();return;}
        $state=json_decode((string)$simulation['state'],true,512,JSON_THROW_ON_ERROR);$state['departure_at']??=$simulation['departure_at'];$now=microtime(true);$last=(new DateTimeImmutable($simulation['last_tick_at']))->format('U.u');
        $wall=max(0,min(10,$now-(float)$last));$delta=$wall*($simulation['mode']==='arcade'?60:1);if($delta<.05){$this->pdo->commit();return;}
        $clockDelta=$delta+(float)($state['clock_remainder_seconds']??0);$wholeSeconds=(int)floor($clockDelta);$state['clock_remainder_seconds']=$clockDelta-$wholeSeconds;$simulated=(new DateTimeImmutable($simulation['simulated_at']))->modify('+'.$wholeSeconds.' seconds');$status=$simulation['status'];
        $this->advanceFatigue($state,$delta,$id,$simulated,$status);
        if($status==='running'&&!empty($state['roadside_rest'])){$state['vehicle']['current_speed']=0;$state['vehicle']['stopped_seconds']+=$delta;$state['roadside_rest_seconds']=($state['roadside_rest_seconds']??0)+$delta;}
        elseif($status==='running'&&$state['current_segment'])$this->advanceVehicle($state,$delta,$id,$simulated,$status,(int)$simulation['random_seed']);
        $this->promoteNotification($state,$status);$this->save($id,$state,$status,$simulated);$this->pdo->commit();
        }catch(\Throwable $error){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$error;}
    }

    public function act(string $id,int $userId,string $action,array $payload,bool $isSuperadmin=false):void
    {
        $this->pdo->beginTransaction();try{$statement=$this->pdo->prepare('SELECT * FROM simulations WHERE id=? FOR UPDATE');$statement->execute([$id]);$simulation=$statement->fetch();
        $debugAction=$action==='debug_flat_tire';
        if(!$simulation||((int)$simulation['user_id']!==$userId&&!($isSuperadmin&&$debugAction))){$this->pdo->rollBack();throw new RuntimeException('Simulation not found.');}
        if($debugAction&&!$isSuperadmin){$this->pdo->rollBack();throw new RuntimeException('That action is restricted to the superadmin.');}
        if(in_array($simulation['status'],['completed','failed'],true)){ $this->pdo->rollBack();throw new RuntimeException('This simulation has ended.'); }
        $state=json_decode((string)$simulation['state'],true,512,JSON_THROW_ON_ERROR);$state['departure_at']??=$simulation['departure_at'];$status=$simulation['status'];$at=new DateTimeImmutable($simulation['simulated_at']);
        if(!empty($state['roadside_rest'])&&$action!=='change_driver')throw new RuntimeException('Choose an available driver when the crew is ready to continue.');
        if(in_array($state['pending_decision']['type']??'',['event','confirmation','fuel_game','tire_game'],true)&&!in_array($action,['acknowledge_event','fuel_change_driver','fuel_minigame','tire_minigame'],true))throw new RuntimeException('Complete the active interaction first.');
        if($action==='debug_flat_tire'&&$status==='running'&&!empty($state['current_segment'])){$flat=['type'=>'flat_tire','delay'=>0.0,'service_seconds'=>0,'mitigated'=>false,'jailed'=>false,'ends_run'=>false,'countermeasure'=>'none','countermeasure_outcome'=>'normal','speed_cap'=>null,'weather'=>null,'weather_miles'=>0.0,'wildlife_miles'=>0.0,'thermal_camera'=>false,'icon'=>null,'mpg_multiplier'=>1.0];array_unshift($state['current_segment']['pending_obstacles'],$flat);$this->activateObstacle($state,$id,$at,$status);}
        elseif($action==='choose_segment'&&$status==='awaiting_route'){$name=(string)($payload['segment']??'');if(!in_array($name,array_column($state['choices'],'name'),true))throw new RuntimeException('Choose an available onward segment.');$state['pending_decision']=null;$status=$this->startSegment($state,$name,$at,$id,(int)$simulation['random_seed']);}
        elseif($action==='pause'&&$status==='running'){$status='paused';$state['user_paused']=true;$this->event($id,$at,'paused');}
        elseif($action==='resume'&&$status==='paused'&&empty($state['pending_decision'])){$status='running';$state['user_paused']=false;$state['vehicle']['current_speed']=$this->segmentSpeed($state);$this->event($id,$at,'resumed');}
        elseif($action==='target_speed'){$returnStatus=$status;$previousSpeed=(float)($state['last_speed_for_warning']??$this->vehicleSpeedLimit($state['vehicle']));$state['vehicle']['target_speed']=max(20,min(250,(float)($payload['speed']??$state['vehicle']['target_speed'])));if($state['current_segment']){$weatherCaps=['fog'=>45.0,'rain'=>80.0,'ice'=>35.0,'snow'=>65.0];$legacyCap=empty($state['active_weather'])?($weatherCaps[$state['current_segment']['weather']??'']??INF):INF;$state['current_segment']['cruising_speed']=min($this->vehicleSpeedLimit($state['vehicle']),$legacyCap);if($status==='running')$state['vehicle']['current_speed']=$this->segmentSpeed($state);}$actualSpeed=$this->vehicleSpeedLimit($state['vehicle']);$state['last_speed_for_warning']=$actualSpeed;$warnings=[];if(in_array($status,['running','paused'],true))foreach([120,145] as $threshold)if($previousSpeed<=$threshold&&$actualSpeed>$threshold)$warnings[]=$threshold;if($warnings){$first=array_shift($warnings);$status='paused';$state['pending_decision']=$this->speedWarningDecision($first,$warnings,$returnStatus);}$this->event($id,$at,'target_speed_changed',['speed'=>$state['vehicle']['target_speed']]);}
        elseif($action==='fuel'&&$status==='running'){if(!empty($state['fuel_stop_pending']))throw new RuntimeException('The crew is already looking for a fuel stop.');if((float)$state['vehicle']['capacity']-(float)$state['vehicle']['fuel']<.01)throw new RuntimeException('The fuel tank is already full.');$status='paused';$state['pending_decision']=['type'=>'confirmation','title'=>'Find the next fuel stop','message'=>'The co-pilot starts scanning signs and exits for a station that can handle the crew. They will pull in at the next suitable fuel stop.','fuel_search_request'=>true];}
        elseif($action==='fuel_change_driver'&&$status==='paused'&&($state['pending_decision']['fuel_stop']??false)){$resumeSpeed=(float)$state['pending_decision']['resume_speed'];$status='awaiting_driver';$state['pending_decision']=['type'=>'driver','forced'=>false,'fuel_stop'=>true,'resume_speed'=>$resumeSpeed];}
        elseif($action==='fuel_minigame'&&$status==='paused'&&($state['pending_decision']['type']??'')==='fuel_game'){
            $step=(string)($payload['step']??'');$pending=&$state['pending_decision'];$phase=(string)($pending['phase']??'');
            if($phase==='card_to_reader'&&$step==='card_reader'){$pending['phase']='payment_prompt';$pending['mistake']=false;}
            elseif($phase==='payment_prompt'&&$step==='payment_button'){$value=(int)($payload['value']??0);$index=(int)($pending['qte_index']??0);$sequence=(array)($pending['qte_sequence']??[]);if($value!==(int)($sequence[$index]??-1)){$pending['qte_index']=0;$pending['mistake']=true;}else{$pending['qte_index']=$index+1;$pending['mistake']=false;if($pending['qte_index']>=count($sequence))$pending['phase']='return_card';}}
            elseif($phase==='return_card'&&$step==='card_wallet'){$pending['phase']='connect_nozzle';}
            elseif($phase==='connect_nozzle'&&$step==='nozzle_car'){$pending['phase']='fueling';$pending['fueling_ready_at']=microtime(true)+6;}
            elseif($phase==='fueling'&&$step==='fueling_complete'&&microtime(true)>=(float)($pending['fueling_ready_at']??INF)){$pending['phase']='return_nozzle';}
            elseif($phase==='return_nozzle'&&$step==='nozzle_pump'){$message=(string)$pending['completion_message'];$resumeSpeed=(float)$pending['resume_speed'];$state['pending_decision']=['type'=>'confirmation','title'=>'Fuel stop complete','message'=>$message,'resume_speed'=>$resumeSpeed,'fuel_stop'=>true];$this->event($id,$at,'fuel_minigame_completed');}
            else throw new RuntimeException('That fueling action is not available yet.');
            unset($pending);
        }
        elseif($action==='tire_minigame'&&$status==='paused'&&($state['pending_decision']['type']??'')==='tire_game'){
            $step=(string)($payload['step']??'');$pending=&$state['pending_decision'];$phase=(string)($pending['phase']??'');$lug=max(0,min(4,(int)($payload['lug']??0)));
            if($phase==='jack_to_car'&&$step==='jack_car')$pending['phase']='raise_car';
            elseif($phase==='raise_car'&&$step==='jack_raised')$pending['phase']='pickup_drill_remove';
            elseif($phase==='pickup_drill_remove'&&$step==='drill_pickup')$pending['phase']='remove_lugs';
            elseif($phase==='remove_lugs'&&$step==='lug_removed'){if(!in_array($lug,$pending['completed_lugs'],true))$pending['completed_lugs'][]=$lug;if(count($pending['completed_lugs'])===5)$pending['phase']='return_drill_remove';}
            elseif($phase==='return_drill_remove'&&$step==='drill_toolbox')$pending['phase']='remove_old_wheel';
            elseif($phase==='remove_old_wheel'&&$step==='old_wheel_removed')$pending['phase']='install_new_wheel';
            elseif($phase==='install_new_wheel'&&$step==='new_wheel_installed'){$pending['phase']='pickup_drill_install';$pending['completed_lugs']=[];}
            elseif($phase==='pickup_drill_install'&&$step==='drill_pickup')$pending['phase']='install_lugs';
            elseif($phase==='install_lugs'&&$step==='lug_installed'){if(!in_array($lug,$pending['completed_lugs'],true))$pending['completed_lugs'][]=$lug;if(count($pending['completed_lugs'])===5)$pending['phase']='return_drill_install';}
            elseif($phase==='return_drill_install'&&$step==='drill_toolbox')$pending['phase']='lower_car';
            elseif($phase==='lower_car'&&$step==='car_lowered')$pending['phase']='return_jack';
            elseif($phase==='return_jack'&&$step==='jack_toolbox')$state['pending_decision']=$pending['event_decision'];
            else throw new RuntimeException('That tire-change action is not available yet.');
            unset($pending);
        }
        elseif($action==='copilot'){$this->assignCopilot($state,(string)($payload['copilot']??''),$id,$at);}
        elseif($action==='use_consumable'&&$status==='running'){
            $type=(string)($payload['consumable']??'');$driverId=(string)($payload['driver']??'');
            if(!in_array($type,['redbull','snack'],true)||empty($state['consumables'][$type]))throw new RuntimeException('That consumable is not available.');
            $driverIndex=null;foreach($state['drivers'] as $index=>$driver)if((string)$driver['id']===$driverId){$driverIndex=$index;break;}
            if($driverIndex===null)throw new RuntimeException('Choose a crew member.');
            $item=&$state['consumables'][$type];$driver=&$state['drivers'][$driverIndex];$used=(int)($driver['consumable_uses'][$type]??0);$maximum=(int)($item['maximum_per_driver']??0);$driverName=(string)$driver['name'];
            if($used>=$maximum){
                $event=$type.'_rejected';$status='paused';$state['pending_decision']=['type'=>'event','event'=>$event,'driver'=>$driverName,'flavor_variant'=>random_int(0,4),'return_status'=>'running'];
                $this->event($id,$at,'consumable_rejected',['consumable'=>$type,'driver'=>$driverName,'reason'=>'maximum_reached','remaining'=>(int)$item['remaining']]);
            }else{
                if((int)$item['remaining']<=0)throw new RuntimeException($type==='snack'?'There are no snacks left.':'The RedBull cooler is empty.');
                $item['remaining']=(int)$item['remaining']-1;$driver['consumable_uses'][$type]=$used+1;$status='paused';
                if($type==='redbull'){
                    $driver['active_effects'][$type]=(float)($driver['active_effects'][$type]??0)+(float)($item['effect_seconds']??7200);
                    $dose=$used+1;$drivingPenalty=$dose===3?10:($dose===4?20:0);if($drivingPenalty>0)$driver['redbull_penalties'][]=['amount'=>$drivingPenalty,'recovery_remaining'=>50.0,'dose'=>$dose];
                    $state['pending_decision']=['type'=>'event','event'=>'redbull_used','driver'=>$driverName,'remaining'=>(int)$item['remaining'],'hours'=>2,'dose'=>$dose,'driving_penalty'=>$drivingPenalty,'flavor_variant'=>random_int(0,4),'return_status'=>'running'];
                    $eventPayload=['consumable'=>$type,'driver'=>$driverName,'remaining'=>(int)$item['remaining'],'duration_seconds'=>(int)($item['effect_seconds']??7200),'dose'=>$dose,'driving_penalty'=>$drivingPenalty];
                }else{
                    $reduction=(float)($item['fatigue_reduction']??5);$before=(float)$driver['fatigue'];$driver['fatigue']=max(0,$before-$reduction);$actual=$before-(float)$driver['fatigue'];$this->recoverRedbullPenalties($driver,$actual,$state,$id,$at);if(($driver['locked_rest']??false)&&$driver['fatigue']<=50)$driver['locked_rest']=false;
                    $state['pending_decision']=['type'=>'event','event'=>'snack_used','driver'=>$driverName,'remaining'=>(int)$item['remaining'],'fatigue_reduction'=>$actual,'flavor_variant'=>random_int(0,4),'return_status'=>'running'];
                    $eventPayload=['consumable'=>$type,'driver'=>$driverName,'remaining'=>(int)$item['remaining'],'fatigue_reduction'=>$actual];
                }
                $this->event($id,$at,'consumable_used',$eventPayload);
            }
            unset($driver,$item);
        }
        elseif($action==='request_driver_change'&&$status==='running'){$resumeSpeed=(float)$state['vehicle']['current_speed'];$status='awaiting_driver';$state['pending_decision']=['type'=>'driver','forced'=>false,'deceleration_seconds'=>(int)ceil(max(0,$resumeSpeed)/5),'resume_speed'=>$resumeSpeed];$this->event($id,$at,'driver_change_requested');}
        elseif($action==='cancel_driver_change'&&$status==='awaiting_driver'&&!($state['pending_decision']['forced']??false)){$status='running';$state['vehicle']['current_speed']=$this->segmentSpeed($state);$state['pending_decision']=null;$this->event($id,$at,'driver_change_cancelled');}
        elseif($action==='rest_roadside'&&$status==='awaiting_driver'&&($state['pending_decision']['forced']??false)){$resumeSpeed=(float)($state['pending_decision']['resume_speed']??$this->segmentSpeed($state));foreach($state['drivers'] as &$driver)$driver['role']='rest';unset($driver);$state['driver_copilot']=false;$state['vehicle']['current_speed']=0;$state['roadside_rest']=true;$state['roadside_rest_seconds']=0.0;$status='running';$state['pending_decision']=['type'=>'driver','forced'=>true,'roadside_rest'=>true,'resume_speed'=>$resumeSpeed];$this->markMapEvent($state,'roadside_rest_started');$this->event($id,$at,'roadside_rest_started');}
        elseif($action==='change_driver'&&($status==='awaiting_driver'||($status==='running'&&!empty($state['roadside_rest'])))){$duringFuel=(bool)($state['pending_decision']['fuel_stop']??false);$roadsideRest=!empty($state['roadside_rest']);$roadsideSeconds=(int)round((float)($state['roadside_rest_seconds']??0));$deceleration=(int)($state['pending_decision']['deceleration_seconds']??0);$previousSpeed=(float)($state['pending_decision']['resume_speed']??$this->segmentSpeed($state));$this->changeDriver($state,(string)($payload['driver']??''),$id,$at);$resumeSpeed=$this->segmentSpeed($state);$this->markMapEvent($state,'driver_change');unset($state['roadside_rest'],$state['roadside_rest_seconds']);if($roadsideRest)$this->event($id,$at,'roadside_rest_ended',['seconds'=>$roadsideSeconds]);if($duringFuel){$state['vehicle']['current_speed']=$resumeSpeed;$status='running';$state['pending_decision']=null;$this->event($id,$at,'driver_change_complete',['seconds'=>0,'during_fuel'=>true]);}else{$acceleration=(int)ceil($previousSpeed/5);$service=120;$total=$deceleration+$service+$acceleration;$this->recordRoleTime($state,$total);$this->advanceConsumableEffects($state,$total,$id,$at);$at=$at->modify('+'.$total.' seconds');$state['vehicle']['stopped_seconds']+=$service;$state['vehicle']['current_speed']=0;$status='paused';$state['pending_decision']=['type'=>'confirmation','title'=>'Driver change complete','message'=>sprintf("The vehicle slowed for %d seconds, the driver change took 120 seconds while stopped, and returning to speed takes %d seconds.\n\n%d minutes %d seconds were added to the run.",$deceleration,$acceleration,intdiv($total,60),$total%60),'resume_speed'=>$resumeSpeed];$this->event($id,$at,'driver_change_complete',['seconds'=>$total]);}}
        elseif($action==='acknowledge_event'&&$status==='paused'&&!empty($state['pending_decision']['fuel_search_request'])){$state['fuel_stop_pending']=['remaining_miles'=>random_int(50,150)/10];$state['pending_decision']=null;$state['vehicle']['current_speed']=$this->segmentSpeed($state);$status='running';$this->event($id,$at,'fuel_stop_requested');}
        elseif($action==='acknowledge_event'&&$status==='paused'&&in_array($state['pending_decision']['type']??'',['event','confirmation'],true)){$pending=$state['pending_decision'];if(!empty($pending['speed_warning'])){$remaining=(array)($pending['remaining_thresholds']??[]);if($remaining){$next=(int)array_shift($remaining);$state['pending_decision']=$this->speedWarningDecision($next,$remaining,(string)($pending['return_status']??'running'));}else{$state['pending_decision']=null;$status=($pending['return_status']??'running')==='paused'?'paused':'running';if($status==='running')$state['vehicle']['current_speed']=$this->segmentSpeed($state);}}else{$penalty=(int)($pending['penalty_seconds']??0);$stationary=(int)($pending['stationary_seconds']??0);$eventType=(string)($pending['event']??'');$contributors=array_unique(array_map('strval',(array)($pending['fatigue_contributors']??[])));if($contributors)foreach($state['drivers'] as &$driver)if(in_array((string)$driver['id'],$contributors,true))$driver['fatigue']=min(100,(float)$driver['fatigue']+5);unset($driver);if(empty($pending['ends_run'])&&in_array($eventType,['road_event','police_event','flat_tire','mechanical_failure'],true))$this->markMapEvent($state,'obstacle_response');if($penalty>0){$this->recordRoleTime($state,$penalty);$this->advanceConsumableEffects($state,$penalty,$id,$at);$at=$at->modify('+'.$penalty.' seconds');}$state['vehicle']['stopped_seconds']+=$stationary;$state['pending_decision']=null;if(!empty($pending['ends_run'])){$state['vehicle']['current_speed']=0;$state['failure_reason']=(string)($pending['failure_reason']??'The crew was taken to jail before reaching Portofino Marina.');$status='failed';$terminalEvent=$eventType==='mechanical_failure'?'mechanical_failure_ended_run':($eventType==='flat_tire'?'flat_tire_ended_run':(in_array($eventType,['crash_event','wildlife_event'],true)?null:'crew_jailed'));if($terminalEvent!==null)$this->event($id,$at,$terminalEvent);}else{$status='running';$state['vehicle']['current_speed']=isset($pending['resume_speed'])?(float)$pending['resume_speed']:$this->segmentSpeed($state);if(!in_array($eventType,['redbull_used','redbull_rejected','redbull_wore_off','snack_used','snack_rejected','redbull_penalty_cleared'],true))$this->event($id,$at,'event_acknowledged',['seconds'=>$penalty,'event'=>$eventType]);}}}
        else throw new RuntimeException('That action is not available right now.');
        $this->promoteNotification($state,$status);$this->save($id,$state,$status,$at);$this->pdo->commit();
        }catch(\Throwable $error){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$error;}
    }

    private function startSegment(array &$state,string $name,DateTimeImmutable $at,string $id,int $seed):string
    {
        $segment=$this->graph->segment($name);if(!$segment||$segment['start']!==$state['node'])throw new RuntimeException('That segment is not a valid continuation.');
        $driver=$this->role($state,'driver');$copilot=$this->role($state,'copilot');if(!$driver)throw new RuntimeException('Assign a driver before departing.');$eventChances=$state['event_chances']??$this->eventChances();
        $conditions=$this->traffic->conditions($segment,$at,$seed+count($state['route']));$speed=$this->vehicleSpeedLimit($state['vehicle']);$obstacleSeed=$seed+count($state['route'])*17;$obstacles=[];$windows=[[.15,.35],[.4,.6],[.65,.9]];foreach($windows as $index=>$window){$eventSeed=$obstacleSeed+$index*101;$span=$window[1]-$window[0];$trigger=$window[0]+(hexdec(substr(hash('sha256','position:'.$eventSeed),0,8))%1001)/1000*$span;$obstacle=$this->obstacle($eventSeed,$driver,$copilot,$segment,$at,$speed,$index===0,$eventChances,$state['equipment']??[],$state['vehicle']);if($obstacle['type'])$obstacles[]=$obstacle+['trigger_fraction'=>$trigger];$trafficSkillTrigger=$window[0]+(hexdec(substr(hash('sha256','invented-position:'.$eventSeed),0,8))%1001)/1000*$span;$obstacles[]=['type'=>'invented_traffic_check','event_seed'=>$eventSeed,'trigger_fraction'=>$trafficSkillTrigger];}usort($obstacles,static fn(array $left,array $right):int=>$left['trigger_fraction']<=>$right['trigger_fraction']);$trafficCap=$trafficCapSeconds=null;$trafficTrigger=.15+(hexdec(substr(hash('sha256','traffic-position:'.$obstacleSeed),0,8))%401)/1000;
        if($conditions['delay_seconds']>=60){$zoneFraction=min(.4,.9-$trafficTrigger);$zoneMiles=max(.001,$segment['distance_miles']*$zoneFraction);$trafficCap=max(5,min(65,$speed*.75,$zoneMiles/(($zoneMiles/$speed)+$conditions['delay_seconds']/3600)));if($trafficCap<$speed)$trafficCapSeconds=$conditions['delay_seconds']/(1-$trafficCap/$speed);}
        $drive=$segment['distance_miles']/$speed*3600+$conditions['delay_seconds'];
        $state['current_segment']=$segment+['elapsed_seconds'=>0.0,'total_seconds'=>$drive,'distance_traveled_miles'=>0.0,'progress_fraction'=>0.0,'speed_trace'=>[],'map_events'=>[],'cruising_speed'=>$speed,'traffic_speed_cap'=>$trafficCap,'traffic_cap_seconds'=>$trafficCapSeconds,'traffic_trigger_fraction'=>$trafficTrigger,'traffic_started'=>false,'traffic_end_elapsed'=>null,'traffic_cap_lifted'=>false,'traffic_delay_seconds'=>$conditions['delay_seconds'],'obstacle_delay_seconds'=>array_sum(array_column($obstacles,'delay')),'traffic_source'=>$conditions['source'],'traffic_samples'=>$conditions['samples'],'status_icon'=>null,'weather'=>null,'mpg_multiplier'=>1.0,'pending_obstacles'=>$obstacles];
        $state['choices']=[];$state['started']=true;$state['vehicle']['current_speed']=$this->segmentSpeed($state);$state['route'][]=$name;
        $this->event($id,$at,'segment_entered',['segment'=>$name,'destination'=>$segment['end'],'traffic_source'=>$conditions['source'],'samples'=>$conditions['samples']]);
        return'running';
    }

    private function advanceVehicle(array &$state,float $delta,string $id,DateTimeImmutable &$at,string &$status,int $seed):void
    {
        $segment=&$state['current_segment'];$speed=max(.1,$this->segmentSpeed($state));$state['vehicle']['current_speed']=$speed;$distance=max(.001,(float)$segment['distance_miles']);$traveled=(float)($segment['distance_traveled_miles']??($distance*min(1,$segment['elapsed_seconds']/max(1,$segment['total_seconds']))));$remainingMiles=max(0,$distance-$traveled);$pendingObstacles=$segment['pending_obstacles']??(!empty($segment['pending_obstacle'])?[$segment['pending_obstacle']]:[]);$hasObstacle=!empty($pendingObstacles);$obstacleAt=$hasObstacle?$distance*(float)$pendingObstacles[0]['trigger_fraction']:INF;$trafficPending=$segment['traffic_speed_cap']!==null&&array_key_exists('traffic_started',$segment)&&!$segment['traffic_started'];$trafficAt=$trafficPending?$distance*(float)$segment['traffic_trigger_fraction']:INF;
        if($hasObstacle&&$traveled+.001>=$obstacleAt){$this->activateObstacle($state,$id,$at,$status);return;}if($trafficPending&&$traveled+.001>=$trafficAt){$this->activateTraffic($state,$id,$at);return;}$nextTrigger=min($obstacleAt,$trafficAt);$untilTriggerSeconds=is_finite($nextTrigger)?max(0,($nextTrigger-$traveled)/$speed*3600):INF;$trafficEnd=(float)($segment['traffic_end_elapsed']??$segment['traffic_cap_seconds']??INF);$trafficActiveNow=$segment['traffic_speed_cap']!==null&&($segment['traffic_started']??true)&&!($segment['traffic_cap_lifted']??false);$untilTrafficEnd=$trafficActiveNow?max(0,$trafficEnd-$segment['elapsed_seconds']):INF;$activeWeather=$state['active_weather']??null;$untilWeatherEnd=$activeWeather?max(0,(float)$activeWeather['remaining_miles']/$speed*3600):INF;$activeInventedTraffic=$state['active_invented_traffic']??null;$untilInventedTrafficEnd=$activeInventedTraffic?max(0,(float)$activeInventedTraffic['remaining_miles']/$speed*3600):INF;$activeWildlife=$state['active_wildlife_slowdown']??null;$untilWildlifeEnd=$activeWildlife?max(0,(float)$activeWildlife['remaining_miles']/$speed*3600):INF;$fuelStopPending=$state['fuel_stop_pending']??null;$untilFuelStop=$fuelStopPending?max(0,(float)$fuelStopPending['remaining_miles']/$speed*3600):INF;$used=min($delta,$remainingMiles/$speed*3600,$untilTriggerSeconds,$untilTrafficEnd,$untilWeatherEnd,$untilInventedTrafficEnd,$untilWildlifeEnd,$untilFuelStop);$miles=min($remainingMiles,$speed*$used/3600);$from=$traveled/$distance;$to=min(1,($traveled+$miles)/$distance);
        $weatherMpg=$activeWeather?(float)$activeWeather['mpg_multiplier']:(float)($segment['mpg_multiplier']??1);$effectiveMpg=$this->vehicleMpg($state['vehicle'],$speed)*max(.1,$weatherMpg);$fuelBurned=$miles/$effectiveMpg;$state['vehicle']['fuel']-=$fuelBurned;$state['run_metrics']['fuel_consumed']=(float)($state['run_metrics']['fuel_consumed']??0)+$fuelBurned;$state['vehicle']['distance_miles']+=$miles;if($fuelStopPending)$state['fuel_stop_pending']['remaining_miles']=max(0,(float)$state['fuel_stop_pending']['remaining_miles']-$miles);$segment['distance_traveled_miles']=$traveled+$miles;$segment['progress_fraction']=$to;$this->traceSpeed($segment,$from,$to,$speed,(float)$state['vehicle']['target_speed']);$segment['elapsed_seconds']+=$used;if($activeWeather){$state['active_weather']['remaining_miles']=max(0,(float)$state['active_weather']['remaining_miles']-$miles);if($state['active_weather']['remaining_miles']<=.001){$cleared=$state['active_weather']['weather'];$weatherMiles=round((float)($state['active_weather']['total_miles']??0),1);$state['active_weather']=null;$this->markMapEvent($state,'obstacle_response');$state['vehicle']['current_speed']=0;$state['pending_decision']=['type'=>'event','event'=>'weather_cleared','weather'=>$cleared,'weather_miles'=>$weatherMiles,'flavor_variant'=>random_int(0,4)];$status='paused';$this->event($id,$at,'weather_cleared',['weather'=>$cleared,'weather_miles'=>$weatherMiles]);return;}}if($activeInventedTraffic){$state['active_invented_traffic']['remaining_miles']=max(0,(float)$state['active_invented_traffic']['remaining_miles']-$miles);if($state['active_invented_traffic']['remaining_miles']<=.001){$blocker=(string)$state['active_invented_traffic']['blocker'];$trafficMiles=(int)$state['active_invented_traffic']['total_miles'];$state['active_invented_traffic']=null;$this->markMapEvent($state,'obstacle_response');$state['vehicle']['current_speed']=$this->segmentSpeed($state);$this->event($id,$at,'invented_traffic_cleared',['blocker'=>$blocker,'miles'=>$trafficMiles,'speed'=>round((float)$state['vehicle']['current_speed'],1)]);}}if($activeWildlife){$state['active_wildlife_slowdown']['remaining_miles']=max(0,(float)$state['active_wildlife_slowdown']['remaining_miles']-$miles);if($state['active_wildlife_slowdown']['remaining_miles']<=.001){$state['active_wildlife_slowdown']=null;$state['vehicle']['current_speed']=$this->segmentSpeed($state);$this->event($id,$at,'wildlife_cleared',['speed'=>round((float)$state['vehicle']['current_speed'],1)]);}}
        if($segment['traffic_speed_cap']!==null&&($segment['traffic_started']??true)&&$segment['elapsed_seconds']>=$trafficEnd){if(!($segment['traffic_cap_lifted']??false)){$segment['traffic_cap_lifted']=true;$state['vehicle']['current_speed']=$this->segmentSpeed($state);$this->event($id,$at,'traffic_cap_lifted',['speed'=>round((float)$state['vehicle']['current_speed'],1)]);}}
        if($hasObstacle&&$segment['distance_traveled_miles']+.001>=$obstacleAt){$this->activateObstacle($state,$id,$at,$status);return;}
        if($trafficPending&&$segment['distance_traveled_miles']+.001>=$trafficAt){$this->activateTraffic($state,$id,$at);return;}
        if($state['vehicle']['fuel']<=0){$state['vehicle']['fuel']=0;$state['vehicle']['current_speed']=0;$state['failure_reason']='The vehicle ran out of fuel before reaching Portofino Marina.';$status='failed';$this->event($id,$at,'out_of_fuel');return;}
        if(!empty($state['fuel_stop_pending'])&&(float)$state['fuel_stop_pending']['remaining_miles']<=.001){unset($state['fuel_stop_pending']);$this->completeFuelStop($state,$id,$at,$status);return;}
        $fuelShare=$state['vehicle']['fuel']/$state['vehicle']['capacity'];if($fuelShare<=.25&&!($state['fuel_warning']??false)){$percent=(int)round($fuelShare*100);$state['fuel_warning']=true;$state['pending_decision']=['type'=>'event','event'=>'fuel_warning','percent'=>$percent];$status='paused';$this->event($id,$at,'fuel_warning',['percent'=>$percent]);return;}
        if($segment['distance_traveled_miles']+.001<$distance)return;
        $state['node']=$segment['end'];$state['vehicle']['current_speed']=0;$state['traveled_segments'][]=['name'=>$segment['name'],'start'=>$segment['start'],'end'=>$segment['end'],'polyline'=>$segment['polyline'],'speed_trace'=>$segment['speed_trace']??[],'map_events'=>$segment['map_events']??[]];$this->event($id,$at,'segment_completed',['segment'=>$segment['name'],'node'=>$state['node']]);$state['current_segment']=null;
        if($state['node']==='portofino'){$departure=new DateTimeImmutable((string)$state['departure_at']);$roleElapsed=max(array_map(static fn(array $driver):float=>(float)($driver['role_seconds']['total']??0),(array)$state['drivers']));$state['finished_elapsed_seconds']=(int)round($roleElapsed>0?$roleElapsed:max(0,$at->getTimestamp()-$departure->getTimestamp()));$state['end_reason']='The crew reached Portofino Marina, CA.';$status='completed';$this->event($id,$at,'arrived_portofino',['distance_miles'=>$state['vehicle']['distance_miles'],'elapsed_seconds'=>$state['finished_elapsed_seconds']]);return;}
        $state['choices']=$this->choicePayload($state['node']);if(count($state['choices'])===1){try{$status=$this->startSegment($state,$state['choices'][0]['name'],$at,$id,$seed+count($state['route']));}catch(RuntimeException $error){$status='failed';$state['failure_reason']='The run ended because supported traffic data was unavailable: '.$error->getMessage();$this->event($id,$at,'traffic_unavailable',['message'=>$error->getMessage()]);}}else{$status='awaiting_route';$state['pending_decision']=['type'=>'route'];$this->event($id,$at,'route_choice_required',['node'=>$state['node']]);}
    }

    private function advanceFatigue(array &$state,float $delta,string $id,DateTimeImmutable $at,string &$status):void
    {
        $this->recordRoleTime($state,$delta);
        $protectedByDriver=$this->advanceConsumableEffects($state,$delta,$id,$at->modify('-'.(int)round($delta).' seconds'));
        foreach($state['drivers'] as &$driver){$before=$driver['fatigue'];$fatigueDelta=max(0,$delta-(float)($protectedByDriver[(string)$driver['id']]??0));
            if($driver['role']==='driver'||$driver['role']==='copilot'){$hours=1+$driver['endurance']*.15;$multiplier=$driver['role']==='copilot'?.5:(!empty($state['driver_copilot'])?2:1);$rate=100/($hours*3600)*$multiplier;$driver['fatigue']=min(100,$driver['fatigue']+$fatigueDelta*$rate);$driver['rest_seconds']=0;}
            else{$restBefore=(float)$driver['rest_seconds'];$driver['rest_seconds']+=$delta;$recovery=$this->restRecoveryTotal((float)$driver['rest_seconds'])-$this->restRecoveryTotal($restBefore);$driver['fatigue']=max(0,$driver['fatigue']-$recovery);$this->recoverRedbullPenalties($driver,$before-(float)$driver['fatigue'],$state,$id,$at);if(($driver['locked_rest']??false)&&$driver['fatigue']<=50)$driver['locked_rest']=false;}
            foreach([25,50,75,100] as $threshold)if($before<$threshold&&$driver['fatigue']>=$threshold)$this->event($id,$at,'fatigue_threshold',['driver'=>$driver['name'],'fatigue'=>$threshold]);
            if($driver['fatigue']>=100&&$driver['role']!=='rest'){$wasDriver=$driver['role']==='driver';$resumeSpeed=(float)$state['vehicle']['current_speed'];$driver['role']='rest';$driver['locked_rest']=true;$driver['rest_seconds']=0;if($wasDriver){$state['driver_copilot']=false;$state['vehicle']['current_speed']=0;$status='awaiting_driver';$state['pending_decision']=['type'=>'driver','forced'=>true,'resume_speed'=>$resumeSpeed];$this->event($id,$at,'driver_exhausted',['driver'=>$driver['name']]);}else{$this->event($id,$at,'copilot_exhausted',['driver'=>$driver['name']]);}}
        }unset($driver);
    }

    private function recordRoleTime(array &$state,float $seconds):void
    {
        if($seconds<=0)return;
        foreach($state['drivers'] as &$driver){$driver['role_seconds']??=['driver'=>0.0,'copilot'=>0.0,'rest'=>0.0,'total'=>0.0];$role=in_array($driver['role']??'rest',['driver','copilot','rest'],true)?$driver['role']:'rest';$driver['role_seconds'][$role]=(float)($driver['role_seconds'][$role]??0)+$seconds;$driver['role_seconds']['total']=(float)($driver['role_seconds']['total']??0)+$seconds;if($role==='driver'&&!empty($state['driver_copilot']))$driver['role_seconds']['copilot']=(float)($driver['role_seconds']['copilot']??0)+$seconds;}unset($driver);
    }

    private function restRecoveryTotal(float $seconds):float
    {
        $hours=max(0,$seconds)/3600;
        return$hours<=2?2*$hours+3*$hours*$hours:16+14*($hours-2);
    }

    private function advanceConsumableEffects(array &$state,float $seconds,string $id,DateTimeImmutable $startAt):array
    {
        $protected=[];if($seconds<=0)return$protected;
        foreach($state['drivers'] as &$driver){$driverId=(string)$driver['id'];$redbullBefore=max(0,(float)($driver['active_effects']['redbull']??0));$protected[$driverId]=min($seconds,$redbullBefore);if($redbullBefore<=0)continue;$driver['active_effects']['redbull']=max(0,$redbullBefore-$seconds);if($driver['active_effects']['redbull']<=0){unset($driver['active_effects']['redbull']);$expiryAt=$startAt->modify('+'.(int)round($redbullBefore).' seconds');$state['notification_queue'][]=['type'=>'event','event'=>'redbull_wore_off','driver'=>(string)$driver['name'],'flavor_variant'=>random_int(0,4)];$this->event($id,$expiryAt,'consumable_wore_off',['consumable'=>'redbull','driver'=>$driver['name']]);}}unset($driver);return$protected;
    }

    private function recoverRedbullPenalties(array &$driver,float $recovery,array &$state,string $id,DateTimeImmutable $at):void
    {
        if($recovery<=0||empty($driver['redbull_penalties']))return;$remaining=[];
        foreach($driver['redbull_penalties'] as $penalty){$penalty['recovery_remaining']=max(0,(float)($penalty['recovery_remaining']??50)-$recovery);if($penalty['recovery_remaining']>0){$remaining[]=$penalty;continue;}$amount=(int)($penalty['amount']??0);$state['notification_queue'][]=['type'=>'event','event'=>'redbull_penalty_cleared','driver'=>(string)$driver['name'],'driving_penalty'=>$amount,'flavor_variant'=>random_int(0,4)];$this->event($id,$at,'consumable_wore_off',['consumable'=>'redbull_penalty','driver'=>$driver['name'],'driving_penalty'=>$amount]);}
        $driver['redbull_penalties']=$remaining;
    }

    private function promoteNotification(array &$state,string &$status):void
    {
        if($status!=='running'||!empty($state['pending_decision'])||empty($state['notification_queue']))return;
        $state['pending_decision']=array_shift($state['notification_queue']);$status='paused';$state['vehicle']['current_speed']=0;
    }

    private function activateObstacle(array &$state,string $id,DateTimeImmutable $at,string &$status):void
    {
        $segment=&$state['current_segment'];if(array_key_exists('pending_obstacles',$segment)){$obstacle=array_shift($segment['pending_obstacles']);}else{$obstacle=$segment['pending_obstacle'];$segment['pending_obstacle']=null;}if($obstacle['type']==='invented_traffic_check'){$currentDriver=$this->role($state,'driver');$driverSkill=$this->effectiveDrivingSkill($currentDriver);$chance=max(0,min(100,(75-$driverSkill)/75*100));$eventSeed=(int)$obstacle['event_seed'];if(($state['active_invented_traffic']??null)||$chance<=0||!$this->eventRoll($eventSeed,'invented_traffic',$chance))return;$blockers=['camper','semi-truck','tour bus','moving van','rental RV'];$obstacle=['type'=>'invented_traffic','delay'=>0.0,'service_seconds'=>0,'mitigated'=>false,'jailed'=>false,'ends_run'=>false,'countermeasure'=>'none','countermeasure_outcome'=>'normal','speed_cap'=>(float)(45+(hexdec(substr(hash('sha256','traffic-cap:'.$eventSeed),0,8))%16)),'weather'=>null,'weather_miles'=>0.0,'icon'=>null,'mpg_multiplier'=>1.0,'blocker'=>$blockers[hexdec(substr(hash('sha256','traffic-blocker:'.$eventSeed),0,8))%count($blockers)],'traffic_miles'=>5+(hexdec(substr(hash('sha256','traffic-distance:'.$eventSeed),0,8))%6),'bypassed'=>!empty($state['equipment']['police_camo']),'fatigue_contributors'=>isset($currentDriver['id'])?[(string)$currentDriver['id']]:[]];}if(!array_key_exists('service_seconds',$obstacle))$obstacle['service_seconds']=0;if(!array_key_exists('weather_miles',$obstacle))$obstacle['weather_miles']=$obstacle['type']==='weather_event'?max(10,(float)$segment['distance_miles']-(float)$segment['distance_traveled_miles']):0.0;$mapType=$obstacle['type']==='weather_event'?'weather_'.$obstacle['weather']:$obstacle['type'];$this->markMapEvent($state,$mapType);if($obstacle['type']==='flat_tire'){$repairableFlats=1+(!empty($state['equipment']['additional_spare'])?1:0);$repaired=(int)($state['flat_tires_repaired']??0);if($repaired>=$repairableFlats){$obstacle['ends_run']=true;$obstacle['spares_remaining']=0;}else{if(!empty($state['equipment']['additional_spare'])&&empty($state['equipment']['additional_spare_consumed']))$state['equipment']['additional_spare_consumed']=true;$state['flat_tires_repaired']=$repaired+1;$obstacle['spares_remaining']=$repairableFlats-$state['flat_tires_repaired'];$crewSkill=$this->crewCopilotSkill($state['drivers']);$obstacle['fatigue_contributors']=array_map(static fn(array $driver):string=>(string)$driver['id'],$state['drivers']);$obstacle['service_seconds']=(int)round(900-300*$crewSkill/100);$transition=2*(int)ceil(max(0,(float)$state['vehicle']['current_speed'])/5);$obstacle['delay']=(float)$obstacle['service_seconds']+$transition;}}
        if($obstacle['type']==='weather_event'){$state['active_weather']=['weather'=>$obstacle['weather'],'icon'=>$obstacle['icon'],'speed_cap'=>$obstacle['speed_cap'],'mpg_multiplier'=>(float)$obstacle['mpg_multiplier'],'remaining_miles'=>(float)$obstacle['weather_miles'],'total_miles'=>(float)$obstacle['weather_miles']];}
        if($obstacle['type']==='invented_traffic'&&!$obstacle['bypassed'])$state['active_invented_traffic']=['blocker'=>$obstacle['blocker'],'speed_cap'=>(float)$obstacle['speed_cap'],'remaining_miles'=>(float)$obstacle['traffic_miles'],'total_miles'=>(float)$obstacle['traffic_miles']];
        if($obstacle['type']==='wildlife_event'&&!$obstacle['ends_run']&&(float)($obstacle['wildlife_miles']??0)>0)$state['active_wildlife_slowdown']=['speed_cap'=>65.0,'remaining_miles'=>(float)$obstacle['wildlife_miles'],'total_miles'=>(float)$obstacle['wildlife_miles']];
        if($obstacle['type']==='crash_event')$obstacle['ends_run']=true;if($obstacle['type']==='police_event')$state['run_metrics']['police_encounters']=array_key_exists('police_encounters',$state['run_metrics'])?(int)$state['run_metrics']['police_encounters']+1:$this->policeEncounterCount($state);$payload=['delay_seconds'=>(int)$obstacle['delay'],'service_seconds'=>(int)$obstacle['service_seconds'],'mitigated'=>$obstacle['mitigated'],'jailed'=>$obstacle['jailed'],'ends_run'=>(bool)($obstacle['ends_run']??false),'spares_remaining'=>(int)($obstacle['spares_remaining']??0),'countermeasure'=>$obstacle['countermeasure']??'none','countermeasure_outcome'=>$obstacle['countermeasure_outcome']??'normal','police_camo'=>!empty($state['equipment']['police_camo']),'thermal_camera'=>(bool)($obstacle['thermal_camera']??false),'driver_saved'=>(bool)($obstacle['driver_saved']??false),'driver_skill'=>(float)($obstacle['driver_skill']??0),'wildlife_miles'=>(float)($obstacle['wildlife_miles']??0),'weather'=>$obstacle['weather'],'weather_miles'=>(float)$obstacle['weather_miles'],'speed_cap'=>$obstacle['speed_cap'],'mpg_multiplier'=>$obstacle['mpg_multiplier'],'blocker'=>$obstacle['blocker']??null,'traffic_miles'=>(int)($obstacle['traffic_miles']??0),'bypassed'=>(bool)($obstacle['bypassed']??false)];$this->event($id,$at,$obstacle['type'],$payload);
        $penalty=in_array($obstacle['type'],['police_event','flat_tire','mechanical_failure','road_event'],true)?(int)$obstacle['delay']:0;$stationary=$obstacle['type']==='police_event'&&($obstacle['countermeasure_outcome']??'normal')==='normal'&&!$obstacle['jailed']?1800:(in_array($obstacle['type'],['flat_tire','mechanical_failure'],true)?(int)$obstacle['service_seconds']:0);$endsRun=(bool)$obstacle['jailed']||(bool)($obstacle['ends_run']??false);$failureReason=$obstacle['type']==='crash_event'?'The run ended in a crash before the crew reached Portofino Marina.':($obstacle['type']==='wildlife_event'&&$endsRun?'A collision with wildlife ended the run before the crew reached Portofino Marina.':($obstacle['type']==='mechanical_failure'&&$endsRun?'A terminal mechanical failure ended the run before reaching Portofino Marina.':($obstacle['type']==='flat_tire'&&$endsRun?'The crew ran out of spare tires before reaching Portofino Marina.':null)));$state['vehicle']['current_speed']=0;$eventDecision=['type'=>'event','event'=>$obstacle['type'],'delay_seconds'=>(int)$obstacle['delay'],'service_seconds'=>(int)$obstacle['service_seconds'],'penalty_seconds'=>$penalty,'stationary_seconds'=>$stationary,'mitigated'=>$obstacle['mitigated'],'jailed'=>$obstacle['jailed'],'ends_run'=>$endsRun,'failure_reason'=>$failureReason,'spares_remaining'=>(int)($obstacle['spares_remaining']??0),'countermeasure'=>$obstacle['countermeasure']??'none','countermeasure_outcome'=>$obstacle['countermeasure_outcome']??'normal','police_camo'=>!empty($state['equipment']['police_camo']),'thermal_camera'=>(bool)($obstacle['thermal_camera']??false),'driver_saved'=>(bool)($obstacle['driver_saved']??false),'driver_skill'=>(float)($obstacle['driver_skill']??0),'wildlife_miles'=>(float)($obstacle['wildlife_miles']??0),'weather'=>$obstacle['weather'],'weather_miles'=>(float)$obstacle['weather_miles'],'speed_cap'=>$obstacle['speed_cap'],'mpg_multiplier'=>$obstacle['mpg_multiplier'],'blocker'=>$obstacle['blocker']??null,'traffic_miles'=>(int)($obstacle['traffic_miles']??0),'bypassed'=>(bool)($obstacle['bypassed']??false),'fatigue_contributors'=>(array)($obstacle['fatigue_contributors']??[]),'flavor_variant'=>random_int(0,4)];$state['pending_decision']=$obstacle['type']==='flat_tire'&&!$endsRun?['type'=>'tire_game','phase'=>'jack_to_car','completed_lugs'=>[],'event_decision'=>$eventDecision]:$eventDecision;$status='paused';
        if(($state['pending_decision']['type']??'')==='tire_game'&&!($state['minigames_enabled']??true))$state['pending_decision']=$eventDecision;
    }

    private function activateTraffic(array &$state,string $id,DateTimeImmutable $at):void
    {
        $segment=&$state['current_segment'];$segment['traffic_started']=true;$segment['traffic_end_elapsed']=$segment['elapsed_seconds']+(float)$segment['traffic_cap_seconds'];$state['vehicle']['current_speed']=$this->segmentSpeed($state);$this->markMapEvent($state,'traffic_event');$this->event($id,$at,'traffic_delay',['seconds'=>(int)round($segment['traffic_delay_seconds']),'base_speed_cap'=>round((float)$segment['traffic_speed_cap'],1),'speed_cap'=>round((float)$state['vehicle']['current_speed'],1),'driver_skill'=>round($this->effectiveDrivingSkill($this->role($state,'driver')),1)]);
    }

    private function assignCopilot(array &$state,string $copilotId,string $id,DateTimeImmutable $at):void
    {
        $current=$this->role($state,'driver');if(!$current)throw new RuntimeException('A driver must be assigned first.');$state['driver_copilot']=false;
        if($copilotId===$current['id']){$others=array_values(array_filter($state['drivers'],static fn(array $driver):bool=>$driver['id']!==$current['id']));$available=array_filter($others,static fn(array $driver):bool=>!($driver['locked_rest']??false)&&$driver['fatigue']<100);if(count($state['drivers'])>1&&$available)throw new RuntimeException('The driver can co-pilot only during a solo run or when every teammate requires rest.');$state['driver_copilot']=true;}
        $found=$copilotId===''||$copilotId===$current['id'];foreach($state['drivers'] as &$driver){if($driver['role']==='driver')continue;if($driver['id']===$copilotId){if(($driver['locked_rest']??false)||$driver['fatigue']>=100)throw new RuntimeException('That teammate must continue resting.');$driver['role']='copilot';$found=true;}else$driver['role']='rest';}unset($driver);
        if(!$found)throw new RuntimeException('Choose a co-pilot from the roster.');$assigned=$copilotId===''?null:($this->role($state,'copilot')['name']??null);$this->event($id,$at,'copilot_changed',['copilot'=>$assigned,'driver_copilot'=>$state['driver_copilot']]);
    }

    private function changeDriver(array &$state,string $driverId,string $id,DateTimeImmutable $at):void
    {
        $current=$this->role($state,'driver');if($current&&$current['id']===$driverId)throw new RuntimeException('Choose a new driver.');$copilot=$this->role($state,'copilot');$copilotId=$copilot['id']??null;$found=false;
        foreach($state['drivers'] as &$driver){if($driver['id']===$driverId){if(($driver['locked_rest']??false)||$driver['fatigue']>=100)throw new RuntimeException('That driver must rest until fatigue reaches 50%.');$driver['role']='driver';$found=true;}elseif($driver['id']===$copilotId)$driver['role']='copilot';elseif($driver['role']==='driver'||$driver['role']==='copilot')$driver['role']='rest';}unset($driver);
        if(!$found)throw new RuntimeException('Choose an available driver.');$state['driver_copilot']=false;$assigned=$this->role($state,'driver');$this->event($id,$at,'driver_changed',['driver'=>$assigned['name']??$driverId]);
    }

    private function completeFuelStop(array &$state,string $id,DateTimeImmutable &$at,string &$status):void
    {
        $resumeSpeed=(float)$state['vehicle']['current_speed'];$startingFuel=(float)$state['vehicle']['fuel'];$deceleration=(int)ceil($resumeSpeed/5);$this->markMapEvent($state,'fuel_stop');$fuel=$this->fuelStop($state,$id,$at);$service=$fuel['seconds'];$acceleration=(int)ceil($resumeSpeed/5);$total=$deceleration+$service+$acceleration;
        $this->recordRoleTime($state,$total);$this->advanceConsumableEffects($state,$total,$id,$at);$at=$at->modify('+'.$total.' seconds');$state['vehicle']['current_speed']=0;$status='paused';
        $sequence=[];for($index=0;$index<4;$index++)$sequence[]=random_int(1,4);
        $message=sprintf("The vehicle slowed for %d seconds, dispensed %.1f gallons at %.1f GPM, spent 60 seconds paying, and needs %d seconds to return to speed.\n\n%d minutes %d seconds were added to the run.",$deceleration,$fuel['gallons'],$fuel['gpm'],$acceleration,intdiv($total,60),$total%60);$state['pending_decision']=($state['minigames_enabled']??true)?['type'=>'fuel_game','phase'=>'card_to_reader','qte_sequence'=>$sequence,'qte_index'=>0,'mistake'=>false,'gallons'=>round($fuel['gallons'],2),'gpm'=>round($fuel['gpm'],1),'starting_fuel'=>round($startingFuel,3),'ending_fuel'=>round((float)$state['vehicle']['fuel'],3),'resume_speed'=>$resumeSpeed,'completion_message'=>$message]:['type'=>'confirmation','title'=>'Fuel stop complete','message'=>$message,'resume_speed'=>$resumeSpeed,'fuel_stop'=>true];
    }

    private function fuelStop(array &$state,string $id,DateTimeImmutable $at):array
    {
        $needed=max(0,$state['vehicle']['capacity']-$state['vehicle']['fuel']);if($needed<.01)throw new RuntimeException('The fuel tank is already full.');$state['run_metrics']['fuel_stops']=(int)($state['run_metrics']['fuel_stops']??0)+1;
        $averageCopilotSkill=$this->crewCopilotSkill($state['drivers']);$gpm=5+11*max(0,$averageCopilotSkill-50)/50;$seconds=(int)round(60+$needed/$gpm*60);$state['vehicle']['fuel']=$state['vehicle']['capacity'];$state['vehicle']['stopped_seconds']+=$seconds;$state['fuel_warning']=false;foreach($state['drivers'] as &$driver)$driver['fatigue']=min(100,(float)$driver['fatigue']+5);unset($driver);
        foreach($state['drivers'] as &$driver)if($driver['role']==='rest')$driver['rest_seconds']=0;unset($driver);
        $this->event($id,$at,'fuel_stop',['gallons'=>round($needed,2),'seconds'=>$seconds,'gpm'=>$gpm]);return['seconds'=>$seconds,'gallons'=>$needed,'gpm'=>$gpm];
    }

    private function obstacle(int $seed,array $driver,?array $copilot,array $segment,DateTimeImmutable $at,float $speed,bool $allowCrash,array $eventChances,array $equipment,array $vehicle):array
    {
        $none=['type'=>null,'delay'=>0.0,'service_seconds'=>0,'mitigated'=>false,'jailed'=>false,'ends_run'=>false,'countermeasure'=>'none','countermeasure_outcome'=>'normal','speed_cap'=>null,'weather'=>null,'weather_miles'=>0.0,'wildlife_miles'=>0.0,'thermal_camera'=>false,'icon'=>null,'mpg_multiplier'=>1.0];
        if($allowCrash&&$this->eventRoll($seed,'crash-base',(float)($eventChances['simulator_crash_base_percent']??1)))return array_replace($none,['type'=>'crash_event']);
        if($allowCrash&&$speed>145&&$this->eventRoll($seed,'crash-145',(float)$eventChances['simulator_crash_145_percent']))return array_replace($none,['type'=>'crash_event']);
        if($allowCrash&&$speed>120&&$this->eventRoll($seed,'crash-120',(float)$eventChances['simulator_crash_120_percent']))return array_replace($none,['type'=>'crash_event']);
        $driverSkill=$this->effectiveDrivingSkill($driver);$weatherTypes=$this->weatherTypes($segment,$at);$availableWeather=array_values(array_filter($weatherTypes,static fn(array $weather):bool=>!in_array($weather['name'],['head_wind','tail_wind'],true)));$hasHeadWind=(bool)array_filter($weatherTypes,static fn(array $weather):bool=>$weather['name']==='head_wind');$hasTailWind=(bool)array_filter($weatherTypes,static fn(array $weather):bool=>$weather['name']==='tail_wind');
        $chances=['weather_event'=>'simulator_weather_percent','flat_tire'=>'simulator_flat_tire_percent','head_wind'=>'simulator_headwind_percent','tail_wind'=>'simulator_tailwind_percent','police_event'=>'simulator_police_percent','road_event'=>'simulator_road_event_percent','wildlife_event'=>'simulator_wildlife_percent'];$candidates=[];
        foreach($chances as $candidate=>$setting){if($candidate==='police_event'&&$speed<=70)continue;if($candidate==='head_wind'&&!$hasHeadWind)continue;if($candidate==='tail_wind'&&!$hasTailWind)continue;if($candidate==='weather_event'&&!$availableWeather)continue;$chance=(float)($eventChances[$setting]??0);if($candidate==='flat_tire'&&!empty($equipment['cruising_tires']))$chance*=.5;if($candidate==='police_event'&&!empty($equipment['radar_scanner']))$chance*=.5;if($this->eventRoll($seed,$candidate,$chance))$candidates[]=$candidate;}
        if($this->eventRoll($seed,'mechanical_failure',max(0,min(100,(float)($vehicle['lemon']??1)))))$candidates[]='mechanical_failure';
        if(!$candidates)return$none;$type=$candidates[hexdec(substr(hash('sha256','event-choice:'.$seed),0,8))%count($candidates)];$roll=hexdec(substr(hash('sha256','occur:'.$seed),0,8))%1000;
        if(in_array($type,['weather_event','head_wind','tail_wind'],true)){$eligible=$type==='weather_event'?$availableWeather:array_values(array_filter($weatherTypes,static fn(array $weather):bool=>$weather['name']===$type));$weather=$eligible[hexdec(substr(hash('sha256','weather:'.$seed),0,8))%count($eligible)];$miles=10+(hexdec(substr(hash('sha256','weather-distance:'.$seed),0,8))%1101)/10;return array_replace($none,['type'=>'weather_event','speed_cap'=>$weather['speed'],'weather'=>$weather['name'],'weather_miles'=>$miles,'icon'=>$weather['icon'],'mpg_multiplier'=>$weather['mpg']]);}
        $copilotSkill=(float)($copilot['copilot']??0);$copilotFatigue=(float)($copilot['fatigue']??0);if($copilotFatigue>50)$copilotSkill*=max(.5,1-($copilotFatigue-50)/100);if($type==='police_event'){$countermeasure=!empty($equipment['radar_jammer'])?'radar_jammer':(!empty($equipment['radio_scanner'])?'radio_scanner':'none');$counterRoll=hexdec(substr(hash('sha256','countermeasure:'.$seed),0,8))%100;$outcome='normal';if($countermeasure==='radio_scanner'&&$counterRoll<50)$outcome='slowdown';elseif($countermeasure==='radar_jammer')$outcome=$counterRoll<25?'slowdown':($counterRoll<50?'normal':'bypass');if(in_array($outcome,['slowdown','bypass'],true)){$delay=$outcome==='slowdown'?60+2*(int)ceil(max(0,$speed-70)/5):0;return array_replace($none,['type'=>$type,'delay'=>$delay,'countermeasure'=>$countermeasure,'countermeasure_outcome'=>$outcome]);}$jailed=!empty($equipment['police_camo'])||$countermeasure==='radar_jammer'||hexdec(substr(hash('sha256','jail:'.$seed),0,8))%2===0;return array_replace($none,['type'=>$type,'delay'=>$jailed?0.0:1800.0,'jailed'=>$jailed,'countermeasure'=>$countermeasure,'countermeasure_outcome'=>'normal']);}
        if($type==='flat_tire')return array_replace($none,['type'=>$type]);
        if($type==='wildlife_event'){$thermalCamera=!empty($equipment['thermal_camera']);$swerveChance=max(0,min(100,($driverSkill-50)*2));$driverSaved=!$thermalCamera&&$this->eventRoll($seed,'wildlife-swerve',$swerveChance);return array_replace($none,['type'=>$type,'ends_run'=>!$thermalCamera&&!$driverSaved,'speed_cap'=>$thermalCamera?65.0:null,'wildlife_miles'=>$thermalCamera?1.0:0.0,'thermal_camera'=>$thermalCamera,'driver_saved'=>$driverSaved,'driver_skill'=>round($driverSkill,1),'fatigue_contributors'=>$driverSaved?[(string)$driver['id']]:[]]);}
        if($type==='mechanical_failure'){$endsRun=hexdec(substr(hash('sha256','mechanical-outcome:'.$seed),0,8))%2===0;if($endsRun)return array_replace($none,['type'=>$type,'ends_run'=>true]);$service=600+($roll%1201);$transition=2*(int)ceil(max(0,$speed)/5);return array_replace($none,['type'=>$type,'delay'=>$service+$transition,'service_seconds'=>$service]);}
        $mitigation=($driverSkill+$copilotSkill)/200;$base=120+($roll%481);$mitigated=$roll%100<round($mitigation*100);$contributors=[(string)$driver['id']];if($copilot&&isset($copilot['id']))$contributors[]=(string)$copilot['id'];return array_replace($none,['type'=>$type,'delay'=>$base*($mitigated?.35:1),'mitigated'=>$mitigated,'fatigue_contributors'=>array_values(array_unique($contributors))]);
    }

    private function choicePayload(string $node):array{return array_map(static fn(array $segment):array=>['name'=>$segment['name'],'start'=>$segment['start'],'end'=>$segment['end'],'start_label'=>self::locationName($segment['start']),'end_label'=>self::locationName($segment['end']),'distance_miles'=>$segment['distance_miles']],$this->graph->onward($node));}
    private function weatherTypes(array $segment,DateTimeImmutable $at):array
    {
        $catalog=['fog'=>['name'=>'fog','speed'=>45.0,'icon'=>'🌫️','mpg'=>1.0],'rain'=>['name'=>'rain','speed'=>80.0,'icon'=>'🌧️','mpg'=>1.0],'ice'=>['name'=>'ice','speed'=>35.0,'icon'=>'🧊','mpg'=>1.0],'snow'=>['name'=>'snow','speed'=>65.0,'icon'=>'🌨️','mpg'=>1.0],'tail_wind'=>['name'=>'tail_wind','speed'=>null,'icon'=>'💨','mpg'=>1.15],'head_wind'=>['name'=>'head_wind','speed'=>null,'icon'=>'🌬️','mpg'=>.85]];$nodes=[$segment['start'],$segment['end']];$touches=static fn(array $region):bool=>(bool)array_intersect($nodes,$region);$east=$touches(['redball','har','you','cole','coln','nash']);$plains=$touches(['stl','big','elr','den']);$mountain=$touches(['big','den','cov']);$west=$touches(['elr','cov','bar','portofino']);$coastal=$touches(['redball','portofino']);$cold=$touches(['redball','har','you','cole','coln','stl','big','den','cov']);$winter=in_array((int)$at->format('n'),[11,12,1,2,3],true);$names=['rain'];if($east||$plains||$coastal)$names[]='fog';if($plains||$mountain||$west){$names[]='tail_wind';$names[]='head_wind';}if($winter&&$cold){$names[]='snow';$names[]='snow';$names[]='ice';}return array_map(static fn(string $name):array=>$catalog[$name],$names);
    }

    private function eventChances():array{$values=$this->settings->all();$defaults=['simulator_crash_base_percent'=>1,'simulator_crash_120_percent'=>14,'simulator_crash_145_percent'=>14,'simulator_weather_percent'=>5,'simulator_flat_tire_percent'=>5,'simulator_headwind_percent'=>1,'simulator_tailwind_percent'=>1,'simulator_police_percent'=>5,'simulator_road_event_percent'=>5,'simulator_wildlife_percent'=>1];foreach($defaults as $key=>$default)$defaults[$key]=max(0,min(100,(float)($values[$key]??$default)));return$defaults;}
    private function speedWarningDecision(int $threshold,array $remaining,string $returnStatus):array{$higher=$threshold===145;return['type'=>'confirmation','speed_warning'=>true,'remaining_thresholds'=>array_values($remaining),'return_status'=>$returnStatus,'title'=>$higher?'Physics has entered the chat':'The road just got serious','message'=>$higher?'Beyond 145 mph, confidence is not a safety system. A second independent crash check now joins the first, and either one can turn the Portofino party into a very short summary screen. The chance of a crash has increased again.':'The car can now run beyond 120 mph. The scenery is blurring, the fuel gauge is nervous, and one bad roll can end the party before Portofino. The chance of a crash has increased.'];}
    private function eventRoll(int $seed,string $event,float $chance):bool{return(hexdec(substr(hash('sha256',$event.':'.$seed),0,8))%10000)<(int)round($chance*100);}
    private function crewCopilotSkill(array $crew):float{$total=0.0;$count=0;foreach($crew as $member){$skill=(float)$member['copilot'];$fatigue=(float)$member['fatigue'];if($fatigue>50)$skill*=max(.5,1-($fatigue-50)/100);$total+=$skill;$count++;}return$count?max(0,min(100,$total/$count)):0.0;}
    private function traceSpeed(array &$segment,float $from,float $to,float $speed,float $target):void{$ratio=$target>0?max(0,min(1,$speed/$target)):0;$trace=&$segment['speed_trace'];$last=array_key_last($trace);if($last!==null&&abs((float)$trace[$last]['ratio']-$ratio)<.005&&abs((float)$trace[$last]['to']-$from)<.002){$trace[$last]['to']=$to;return;}$trace[]=['from'=>$from,'to'=>$to,'ratio'=>$ratio,'speed'=>$speed,'target'=>$target];}
    private function policeEncounterCount(array $state):int{$segments=(array)($state['traveled_segments']??[]);if(!empty($state['current_segment']))$segments[]=$state['current_segment'];$count=0;foreach($segments as $segment)foreach((array)($segment['map_events']??[]) as $event)if(($event['type']??null)==='police_event')$count++;return$count;}
    private function markMapEvent(array &$state,string $type):void{if(!$state['current_segment'])return;$segment=&$state['current_segment'];$fraction=(float)($segment['progress_fraction']??($segment['total_seconds']>0?max(0,min(1,$segment['elapsed_seconds']/$segment['total_seconds'])):0));$segment['map_events'][]=['type'=>$type,'fraction'=>$fraction];}
    private function vehicleSpeedLimit(array $vehicle):float{if(!isset($vehicle['top_speed']))return max(20,(float)$vehicle['target_speed']);$top=(float)(!empty($vehicle['tuned'])?$vehicle['tuned_top_speed']:$vehicle['top_speed']);return max(20,min((float)$vehicle['target_speed'],$top));}
    private function vehicleMpg(array $vehicle,float $speed):float{if(isset($vehicle['mpg']))return max(.1,(float)$vehicle['mpg']);return max(.1,(float)($speed<35?$vehicle['mpg_below_35']:($speed<=70?$vehicle['mpg_35_70']:$vehicle['mpg_above_70'])));}
    private function effectiveDrivingSkill(?array $driver):float{if(!$driver)return 0.0;$penalty=array_sum(array_map(static fn(array $item):float=>(float)($item['amount']??0),(array)($driver['redbull_penalties']??[])));$skill=max(0,(float)($driver['driving']??0)-$penalty);$fatigue=(float)($driver['fatigue']??0);if($fatigue>50)$skill*=max(.5,1-($fatigue-50)/100);return max(0,min(100,$skill));}
    private function segmentSpeed(array $state):float{$segment=$state['current_segment']??null;if(!$segment)return 0.0;$trafficStarted=array_key_exists('traffic_started',$segment)?(bool)$segment['traffic_started']:true;$trafficEnd=(float)($segment['traffic_end_elapsed']??$segment['traffic_cap_seconds']??0);$trafficActive=$segment['traffic_speed_cap']!==null&&$segment['traffic_speed_cap']<$segment['cruising_speed']&&$trafficStarted&&$segment['elapsed_seconds']<$trafficEnd;$segmentLimit=(float)$segment['cruising_speed'];if($trafficActive)$segmentLimit=(float)$segment['traffic_speed_cap']*$this->effectiveDrivingSkill($this->role($state,'driver'))/100;$speed=min($this->vehicleSpeedLimit($state['vehicle']),$segmentLimit);$weather=$state['active_weather']??null;if($weather&&$weather['speed_cap']!==null)$speed=min($speed,(float)$weather['speed_cap']);$inventedTraffic=$state['active_invented_traffic']??null;if($inventedTraffic)$speed=min($speed,(float)$inventedTraffic['speed_cap']);$wildlife=$state['active_wildlife_slowdown']??null;if($wildlife)$speed=min($speed,(float)$wildlife['speed_cap']);return max(5,$speed);}
    private function role(array $state,string $role):?array{foreach($state['drivers'] as $driver)if($driver['role']===$role)return$driver;if($role==='copilot'&&!empty($state['driver_copilot']))return$this->role($state,'driver');return null;}
    private function event(string $id,DateTimeImmutable $at,string $type,array $payload=[]):void{$this->pdo->prepare('INSERT INTO simulation_events(simulation_id,simulated_at,type,payload) VALUES (?,?,?,?::jsonb)')->execute([$id,$at->format(DATE_ATOM),$type,json_encode($payload,JSON_THROW_ON_ERROR)]);}
    private function save(string $id,array $state,string $status,DateTimeImmutable $at):void{$finished=in_array($status,['completed','failed'],true)?',finished_at=now()':'';$sql="UPDATE simulations SET state=?::jsonb,status=?,simulated_at=?,updated_at=now(),last_tick_at=now(),version=version+1".$finished.' WHERE id=?';$this->pdo->prepare($sql)->execute([json_encode($state,JSON_THROW_ON_ERROR),$status,$at->format(DATE_ATOM),$id]);}
}
